// The server.properties keys shown under Advanced settings, grouped, with
// their type, Minecraft's default (used when a key is not in the file yet)
// and a label and one-line explanation in English and Vietnamese. Keys
// covered by the basic cards (online-mode, max-players, gamemode,
// difficulty, pvp, allow-flight, motd, spawn-protection) are not listed.
// Keys a server has that are not listed here appear under "Other" as text.
window.PROP_GROUPS = [
  {id: 'world', icon: 'public', en: 'World', vi: 'Thế giới'},
  {id: 'players', icon: 'group', en: 'Players', vi: 'Người chơi'},
  {id: 'performance', icon: 'speed', en: 'Performance', vi: 'Hiệu năng'},
  {id: 'network', icon: 'lan', en: 'Network', vi: 'Mạng'},
  {id: 'remote', icon: 'terminal', en: 'Remote control', vi: 'Điều khiển từ xa'},
  {id: 'pack', icon: 'palette', en: 'Resource pack and data packs', vi: 'Gói tài nguyên và gói dữ liệu'},
  {id: 'other', icon: 'more_horiz', en: 'Other', vi: 'Khác'},
];

window.PROP_SCHEMA = [
  // World
  {key: 'level-name', group: 'world', type: 'text', def: 'world',
    en: ['World folder', 'The folder the world is saved in. A new name starts a new world; the old one is kept.'],
    vi: ['Thư mục thế giới', 'Thư mục lưu thế giới. Đổi tên sẽ tạo thế giới mới; thế giới cũ vẫn được giữ.']},
  {key: 'level-seed', group: 'world', type: 'text', def: '',
    en: ['World seed', 'Used only when a new world is made. Leave empty for a random one.'],
    vi: ['Seed thế giới', 'Chỉ dùng khi tạo thế giới mới. Để trống để lấy ngẫu nhiên.']},
  {key: 'level-type', group: 'world', type: 'text', def: 'minecraft:normal',
    suggest: ['minecraft:normal', 'minecraft:flat', 'minecraft:large_biomes', 'minecraft:amplified', 'minecraft:single_biome_surface'],
    en: ['World type', 'Used only when a new world is made. Some modpacks use their own type.'],
    vi: ['Kiểu thế giới', 'Chỉ dùng khi tạo thế giới mới. Một số modpack có kiểu riêng.']},
  {key: 'generator-settings', group: 'world', type: 'text', def: '{}',
    en: ['Generator settings', 'Settings for custom world types, in JSON. Leave it unless a guide says otherwise.'],
    vi: ['Cài đặt tạo thế giới', 'Cài đặt cho kiểu thế giới tùy chỉnh, dạng JSON. Giữ nguyên nếu không có hướng dẫn.']},
  {key: 'generate-structures', group: 'world', type: 'bool', def: 'true',
    en: ['Generate structures', 'Villages, temples and other structures appear in new areas.'],
    vi: ['Tạo công trình', 'Làng, đền và các công trình khác xuất hiện ở vùng mới.']},
  {key: 'allow-nether', group: 'world', type: 'bool', def: 'true',
    en: ['Nether', 'Players can travel to the Nether.'],
    vi: ['Nether', 'Người chơi có thể sang Nether.']},
  {key: 'hardcore', group: 'world', type: 'bool', def: 'false',
    en: ['Hardcore', 'Difficulty is locked to hard, and players who die become spectators.'],
    vi: ['Hardcore', 'Độ khó luôn là Khó, và người chơi chết sẽ thành khán giả.']},
  {key: 'spawn-monsters', group: 'world', type: 'bool', def: 'true',
    en: ['Monsters', 'Hostile mobs appear.'],
    vi: ['Quái vật', 'Quái thù địch xuất hiện.']},
  {key: 'spawn-animals', group: 'world', type: 'bool', def: 'true',
    en: ['Animals', 'Animals appear. Minecraft 1.21.2 and newer ignore this.'],
    vi: ['Động vật', 'Động vật xuất hiện. Minecraft 1.21.2 trở lên bỏ qua cài đặt này.']},
  {key: 'spawn-npcs', group: 'world', type: 'bool', def: 'true',
    en: ['Villagers', 'Villagers appear. Minecraft 1.21.2 and newer ignore this.'],
    vi: ['Dân làng', 'Dân làng xuất hiện. Minecraft 1.21.2 trở lên bỏ qua cài đặt này.']},
  {key: 'max-world-size', group: 'world', type: 'int', def: '29999984', min: 1, max: 29999984,
    en: ['World border radius', 'How far from the center players can go, in blocks.'],
    vi: ['Bán kính biên giới', 'Người chơi đi được bao xa từ tâm, tính bằng khối.']},

  // Players
  {key: 'white-list', group: 'players', type: 'bool', def: 'false',
    en: ['Whitelist', 'Only players on the whitelist can join. Add them with the command: whitelist add <name>.'],
    vi: ['Danh sách trắng', 'Chỉ người trong danh sách trắng mới vào được. Thêm bằng lệnh: whitelist add <tên>.']},
  {key: 'enforce-whitelist', group: 'players', type: 'bool', def: 'false',
    en: ['Kick players not on the whitelist', 'When the whitelist is turned on or reloaded, players not on it are kicked.'],
    vi: ['Đá người ngoài danh sách trắng', 'Khi bật hoặc tải lại danh sách trắng, người không có tên sẽ bị đá ra.']},
  {key: 'force-gamemode', group: 'players', type: 'bool', def: 'false',
    en: ['Force game mode', "Players are put back in the server's game mode every time they join."],
    vi: ['Ép chế độ chơi', 'Mỗi lần vào, người chơi được đưa về chế độ chơi của máy chủ.']},
  {key: 'player-idle-timeout', group: 'players', type: 'int', def: '0', min: 0, max: 100000,
    en: ['Kick idle players after (minutes)', 'Players who do nothing this long are kicked. 0 never kicks.'],
    vi: ['Đá người treo máy sau (phút)', 'Người không làm gì trong khoảng này sẽ bị đá. 0 là không bao giờ.']},
  {key: 'op-permission-level', group: 'players', type: 'int', def: '4', min: 0, max: 4,
    en: ['Admin permission level', 'What admins (ops) can do by default, from 0 (nothing) to 4 (everything).'],
    vi: ['Quyền của quản trị viên', 'Quản trị viên (op) làm được gì, từ 0 (không gì) đến 4 (mọi thứ).']},
  {key: 'function-permission-level', group: 'players', type: 'int', def: '2', min: 1, max: 4,
    en: ['Data pack function permission level', 'Permission level functions from data packs run with, from 1 to 4.'],
    vi: ['Quyền của hàm gói dữ liệu', 'Mức quyền khi chạy hàm từ gói dữ liệu, từ 1 đến 4.']},
  {key: 'hide-online-players', group: 'players', type: 'bool', def: 'false',
    en: ['Hide player names', 'The server list shows how many play, but not who.'],
    vi: ['Ẩn tên người chơi', 'Danh sách máy chủ chỉ hiện số người chơi, không hiện tên.']},
  {key: 'enforce-secure-profile', group: 'players', type: 'bool', def: 'true',
    en: ['Require signed chat', 'Players need a Mojang-signed profile to chat. Turn off if some players cannot chat.'],
    vi: ['Bắt buộc chat có chữ ký', 'Cần hồ sơ có chữ ký của Mojang để chat. Tắt nếu có người không chat được.']},
  {key: 'prevent-proxy-connections', group: 'players', type: 'bool', def: 'false',
    en: ['Block VPN and proxy connections', 'Kicks players whose connection comes from somewhere other than their Mojang login.'],
    vi: ['Chặn VPN và proxy', 'Đá người có kết nối đến từ nơi khác với nơi đăng nhập Mojang.']},
  {key: 'log-ips', group: 'players', type: 'bool', def: 'true',
    en: ['Log IP addresses', "Save players' IP addresses in the server log when they join."],
    vi: ['Ghi địa chỉ IP', 'Lưu địa chỉ IP của người chơi vào nhật ký khi họ vào.']},

  // Performance
  {key: 'view-distance', group: 'performance', type: 'int', def: '10', min: 3, max: 32,
    en: ['View distance (chunks)', 'How far players can see. Lower helps lag with big modpacks.'],
    vi: ['Tầm nhìn (chunk)', 'Người chơi nhìn được bao xa. Giảm xuống giúp đỡ lag với modpack lớn.']},
  {key: 'simulation-distance', group: 'performance', type: 'int', def: '10', min: 3, max: 32,
    en: ['Simulation distance (chunks)', 'How far around players mobs move and crops grow. Lower helps lag.'],
    vi: ['Khoảng mô phỏng (chunk)', 'Trong khoảng này quái di chuyển và cây lớn. Giảm xuống giúp đỡ lag.']},
  {key: 'entity-broadcast-range-percentage', group: 'performance', type: 'int', def: '100', min: 10, max: 1000,
    en: ['Entity view range (%)', 'How far away players see mobs and items, as a percent of normal.'],
    vi: ['Tầm thấy thực thể (%)', 'Người chơi thấy quái và vật phẩm ở xa bao nhiêu, theo phần trăm so với bình thường.']},
  {key: 'network-compression-threshold', group: 'performance', type: 'int', def: '256', min: -1, max: 1000000,
    en: ['Network compression threshold (bytes)', 'Bigger packets are compressed. Lower saves bandwidth, higher saves CPU. -1 turns it off.'],
    vi: ['Ngưỡng nén mạng (byte)', 'Gói lớn hơn sẽ được nén. Thấp tiết kiệm băng thông, cao tiết kiệm CPU. -1 là tắt.']},
  {key: 'max-tick-time', group: 'performance', type: 'int', def: '60000', min: -1, max: 100000000,
    en: ['Watchdog time (ms)', 'The server stops itself if one tick takes longer. Big modpacks may need more, or -1 to turn it off.'],
    vi: ['Thời gian giám sát (ms)', 'Máy chủ tự dừng nếu một tick lâu hơn mức này. Modpack lớn có thể cần nhiều hơn, hoặc -1 để tắt.']},
  {key: 'max-chained-neighbor-updates', group: 'performance', type: 'int', def: '1000000', min: -1, max: 100000000,
    en: ['Max chained block updates', 'Limit for chain reactions of block updates, such as big redstone machines. -1 removes it.'],
    vi: ['Giới hạn cập nhật khối liên tiếp', 'Giới hạn chuỗi cập nhật khối, như máy redstone lớn. -1 là bỏ giới hạn.']},
  {key: 'rate-limit', group: 'performance', type: 'int', def: '0', min: 0, max: 100000,
    en: ['Packet rate limit', 'Kicks players who send more packets per second than this. 0 turns it off.'],
    vi: ['Giới hạn gói tin', 'Đá người gửi nhiều gói tin mỗi giây hơn mức này. 0 là tắt.']},
  {key: 'pause-when-empty-seconds', group: 'performance', type: 'int', def: '60', min: -1, max: 100000,
    en: ['Pause when empty after (seconds)', 'The world pauses this long after the last player leaves. 0 or less never pauses. Minecraft 1.21.2 and newer.'],
    vi: ['Tạm dừng khi vắng sau (giây)', 'Thế giới tạm dừng sau khoảng này khi người cuối rời đi. 0 trở xuống là không dừng. Minecraft 1.21.2 trở lên.']},
  {key: 'sync-chunk-writes', group: 'performance', type: 'bool', def: 'true',
    en: ['Save world files right away', 'Safer if the PC crashes, but slower on some disks.'],
    vi: ['Lưu tệp thế giới ngay', 'An toàn hơn khi máy bị treo, nhưng chậm hơn trên một số ổ đĩa.']},
  {key: 'region-file-compression', group: 'performance', type: 'enum', def: 'deflate', options: ['deflate', 'lz4', 'none'],
    en: ['World file compression', 'lz4 is faster but uses more disk space. Minecraft 1.20.5 and newer.'],
    vi: ['Nén tệp thế giới', 'lz4 nhanh hơn nhưng tốn ổ đĩa hơn. Minecraft 1.20.5 trở lên.']},
  {key: 'use-native-transport', group: 'performance', type: 'bool', def: 'true',
    en: ['Faster networking on Linux', 'Uses Linux-only network code. Has no effect on Windows.'],
    vi: ['Mạng nhanh hơn trên Linux', 'Dùng mã mạng riêng của Linux. Không có tác dụng trên Windows.']},

  // Network
  {key: 'server-port', group: 'network', type: 'int', def: '25565', min: 1, max: 65535,
    en: ['Server port', 'The port friends connect to. Changing it changes the address you share.'],
    vi: ['Cổng máy chủ', 'Cổng bạn bè kết nối. Đổi cổng sẽ đổi địa chỉ bạn gửi cho họ.']},
  {key: 'server-ip', group: 'network', type: 'text', def: '',
    en: ['Listen on IP', 'Leave empty to accept connections on every network. Set it only if a guide tells you to.'],
    vi: ['Nghe trên IP', 'Để trống để nhận kết nối từ mọi mạng. Chỉ điền khi có hướng dẫn.']},
  {key: 'enable-status', group: 'network', type: 'bool', def: 'true',
    en: ['Show in the server list', "Friends see the name and player count in their list. When off, it looks offline but can still be joined."],
    vi: ['Hiện trong danh sách máy chủ', 'Bạn bè thấy tên và số người chơi. Khi tắt, máy chủ trông như đang tắt nhưng vẫn vào được.']},
  {key: 'enable-query', group: 'network', type: 'bool', def: 'false',
    en: ['Query', 'Answers server-list websites that ask for player counts (GameSpy4 query).'],
    vi: ['Query', 'Trả lời các trang danh sách máy chủ hỏi số người chơi (GameSpy4 query).']},
  {key: 'query.port', group: 'network', type: 'int', def: '25565', min: 1, max: 65535,
    en: ['Query port', 'The port for query.'],
    vi: ['Cổng query', 'Cổng dùng cho query.']},
  {key: 'accepts-transfers', group: 'network', type: 'bool', def: 'false',
    en: ['Accept transfers', 'Other servers can send players here with the /transfer command. Minecraft 1.20.5 and newer.'],
    vi: ['Nhận chuyển máy chủ', 'Máy chủ khác có thể chuyển người chơi sang bằng lệnh /transfer. Minecraft 1.20.5 trở lên.']},

  // Remote control
  {key: 'enable-rcon', group: 'remote', type: 'bool', def: 'false',
    en: ['Remote control (RCON)', 'Lets tools run commands over the network with a password.'],
    vi: ['Điều khiển từ xa (RCON)', 'Cho công cụ chạy lệnh qua mạng bằng mật khẩu.']},
  {key: 'rcon.port', group: 'remote', type: 'int', def: '25575', min: 1, max: 65535,
    en: ['RCON port', 'The port for remote control.'],
    vi: ['Cổng RCON', 'Cổng dùng cho điều khiển từ xa.']},
  {key: 'rcon.password', group: 'remote', type: 'secret', def: '',
    en: ['RCON password', 'Password for remote control. Use a long one.'],
    vi: ['Mật khẩu RCON', 'Mật khẩu điều khiển từ xa. Hãy dùng mật khẩu dài.']},
  {key: 'broadcast-rcon-to-ops', group: 'remote', type: 'bool', def: 'true',
    en: ['Show remote commands to admins', 'Admins in the game see commands sent through RCON.'],
    vi: ['Báo lệnh từ xa cho quản trị viên', 'Quản trị viên trong game thấy lệnh gửi qua RCON.']},
  {key: 'broadcast-console-to-ops', group: 'remote', type: 'bool', def: 'true',
    en: ['Show console commands to admins', 'Admins in the game see commands typed in the server messages.'],
    vi: ['Báo lệnh bảng điều khiển cho quản trị viên', 'Quản trị viên trong game thấy lệnh gõ ở nhật ký máy chủ.']},
  {key: 'enable-command-block', group: 'remote', type: 'bool', def: 'false',
    en: ['Command blocks', 'Command blocks can run commands.'],
    vi: ['Khối lệnh', 'Khối lệnh được phép chạy lệnh.']},
  {key: 'enable-jmx-monitoring', group: 'remote', type: 'bool', def: 'false',
    en: ['JMX monitoring', 'Shares server timings with Java monitoring tools. For advanced users.'],
    vi: ['Giám sát JMX', 'Chia sẻ thời gian xử lý với công cụ giám sát Java. Dành cho người dùng nâng cao.']},

  // Resource pack and data packs
  {key: 'resource-pack', group: 'pack', type: 'text', def: '',
    en: ['Resource pack link', 'A direct download link to a resource pack players are offered when they join.'],
    vi: ['Link gói tài nguyên', 'Link tải trực tiếp gói tài nguyên được mời dùng khi người chơi vào.']},
  {key: 'resource-pack-sha1', group: 'pack', type: 'text', def: '',
    en: ['Resource pack SHA-1', 'Checksum of the resource pack, so players can check the download.'],
    vi: ['SHA-1 của gói tài nguyên', 'Mã kiểm tra của gói tài nguyên để kiểm tra bản tải về.']},
  {key: 'resource-pack-id', group: 'pack', type: 'text', def: '',
    en: ['Resource pack ID', 'A UUID that identifies the resource pack.'],
    vi: ['ID gói tài nguyên', 'UUID để nhận biết gói tài nguyên.']},
  {key: 'resource-pack-prompt', group: 'pack', type: 'text', def: '',
    en: ['Resource pack message', 'Text shown when players are asked to use the resource pack.'],
    vi: ['Lời mời dùng gói tài nguyên', 'Dòng chữ hiện khi mời người chơi dùng gói tài nguyên.']},
  {key: 'require-resource-pack', group: 'pack', type: 'bool', def: 'false',
    en: ['Require the resource pack', 'Players who decline it are disconnected.'],
    vi: ['Bắt buộc gói tài nguyên', 'Người từ chối sẽ bị ngắt kết nối.']},
  {key: 'initial-enabled-packs', group: 'pack', type: 'text', def: 'vanilla',
    en: ['Data packs turned on', 'Data packs enabled when a new world is made, separated by commas.'],
    vi: ['Gói dữ liệu bật', 'Gói dữ liệu được bật khi tạo thế giới mới, cách nhau bằng dấu phẩy.']},
  {key: 'initial-disabled-packs', group: 'pack', type: 'text', def: '',
    en: ['Data packs turned off', 'Data packs disabled when a new world is made, separated by commas.'],
    vi: ['Gói dữ liệu tắt', 'Gói dữ liệu bị tắt khi tạo thế giới mới, cách nhau bằng dấu phẩy.']},

  // Other
  {key: 'bug-report-link', group: 'other', type: 'text', def: '',
    en: ['Bug report link', 'A web address shown on the disconnect screen for reporting problems.'],
    vi: ['Link báo lỗi', 'Địa chỉ web hiện ở màn hình mất kết nối để báo lỗi.']},
  {key: 'text-filtering-config', group: 'other', type: 'text', def: '',
    en: ['Chat filter config', 'For chat filtering services. Leave empty.'],
    vi: ['Cấu hình lọc chat', 'Dành cho dịch vụ lọc chat. Để trống.']},
  {key: 'text-filtering-version', group: 'other', type: 'int', def: '0', min: 0, max: 100,
    en: ['Chat filter version', 'For chat filtering services.'],
    vi: ['Phiên bản lọc chat', 'Dành cho dịch vụ lọc chat.']},
];
