package installer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/bhhoang/IDISMAM/internal/runtime"
	"github.com/bhhoang/IDISMAM/pkg/logger"
)

// runScriptMarker identifies run scripts written by WriteRunScripts, which
// may be regenerated; any other run script belongs to the user or the pack.
const runScriptMarker = "Generated by mcpackctl"

// legacyRunScriptMarker identifies the run.sh written by earlier versions,
// which pointed Fabric and pre-1.17 Forge servers at a nonexistent target.
const legacyRunScriptMarker = "# Minecraft server startup script"

const userJVMArgsHeader = "# JVM arguments for this server, separated by spaces or newlines.\n" +
	"# Lines starting with # are ignored.\n" +
	"# Set the maximum RAM with -Xmx, e.g. -Xmx4G (mcpackctl setup --ram 4G writes it here).\n"

// WriteRunScripts writes run.sh and run.bat for servers started with
// "java -jar" (Fabric, Forge before 1.17), whose installers provide none.
// Forge 1.17+ and NeoForge installers write their own, which are kept.
//
// The scripts read JVM options from user_jvm_args.txt, created here when
// missing, so the heap is set in one place for every loader. The file is
// expanded by the script rather than passed as an @-file, which Java 8 does
// not support. Existing run scripts are only replaced when mcpackctl wrote
// them.
func WriteRunScripts(serverDir string) error {
	if runtime.UsesArgsFiles(serverDir) {
		return nil
	}
	jar, err := runtime.ServerJar(serverDir)
	if err != nil {
		return fmt.Errorf("write run scripts: %w", err)
	}

	userArgs := filepath.Join(serverDir, "user_jvm_args.txt")
	if _, err := os.Stat(userArgs); os.IsNotExist(err) {
		if err := os.WriteFile(userArgs, []byte(userJVMArgsHeader), 0o644); err != nil {
			return fmt.Errorf("write user_jvm_args.txt: %w", err)
		}
	}

	// Each script starts java with a plain "java ..." line, which
	// UsePortableJava later points at a downloaded JDK.
	sh := "#!/usr/bin/env sh\n" +
		"# " + runScriptMarker + ". JVM options such as -Xmx go in user_jvm_args.txt.\n" +
		"cd \"$(dirname \"$0\")\" || exit 1\n" +
		"java $(grep -v '^[[:space:]]*#' user_jvm_args.txt 2>/dev/null) -jar " + jar + " nogui \"$@\"\n"
	bat := "@echo off\r\n" +
		"REM " + runScriptMarker + ". JVM options such as -Xmx go in user_jvm_args.txt.\r\n" +
		"cd /d \"%~dp0\"\r\n" +
		"set \"JVM_ARGS=\"\r\n" +
		"if exist user_jvm_args.txt for /f \"usebackq eol=# delims=\" %%a in (\"user_jvm_args.txt\") do call set \"JVM_ARGS=%%JVM_ARGS%% %%a\"\r\n" +
		"java %JVM_ARGS% -jar " + jar + " nogui %*\r\n" +
		"pause\r\n"

	if err := writeRunScript(filepath.Join(serverDir, "run.sh"), sh, 0o755); err != nil {
		return err
	}
	return writeRunScript(filepath.Join(serverDir, "run.bat"), bat, 0o644)
}

// writeRunScript writes content to path unless path already holds a script
// that mcpackctl did not generate.
func writeRunScript(path, content string, perm os.FileMode) error {
	existing, err := os.ReadFile(path)
	if err == nil && !strings.Contains(string(existing), runScriptMarker) &&
		!strings.Contains(string(existing), legacyRunScriptMarker) {
		logger.Get().Info().Str("script", path).Msg("keeping existing run script")
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", filepath.Base(path), err)
	}
	if err := os.WriteFile(path, []byte(content), perm); err != nil {
		return fmt.Errorf("write %s: %w", filepath.Base(path), err)
	}
	return nil
}
